# -*- coding: utf-8 -*-
"""GradioTestApp1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p_Av_QQbatXVTA8kE3xK3hiZ08CL0UK3
"""

# !pip install -q gradio

# !pip install -q transformers

# !pip install -q sentencepiece

# !pip install -q bert-extractive-summarizer

import gradio as gr
import transformers
import sentencepiece
from summarizer import Summarizer

bert_model=Summarizer()

def SummarizeText(inp):  
   
    summary_generated = bert_model(inp)
#     print(summary_generated)
    return summary_generated

iface = gr.Interface(
  fn=SummarizeText, 
  inputs=[gr.inputs.Textbox(label="Abstract (*Enter paragraphs)",lines=10, placeholder="Enter abstract text here...") ],
    
  outputs=[
           gr.outputs.Textbox(label=" Summary-1  (Bert)") ],title= "Auto summarization and Summary comparision(beta)"  )
iface.launch(debug=True)