# -*- coding: utf-8 -*-
"""GradioTestApp1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p_Av_QQbatXVTA8kE3xK3hiZ08CL0UK3
"""

# !pip install -q gradio

!pip install -q gradio
!pip install -q transformers
!pip install -q sentencepiece
!pip install -q bert-extractive-summarizer

# !pip install -q transformers

# !pip install -q sentencepiece

# !pip install -q bert-extractive-summarizer

import gradio as gr
import transformers
import sentencepiece
from summarizer import Summarizer

bert_model=Summarizer()

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

# model = AutoModelForSeq2SeqLM.from_pretrained("microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract")
model = AutoModelForSeq2SeqLM.from_pretrained("google/pegasus-pubmed")
tokenizer = AutoTokenizer.from_pretrained("google/pegasus-pubmed")



# from transformers import pipeline

# summarizer = pipeline("summarization")



pegasus_large_covid_tokenizer = AutoTokenizer.from_pretrained("mayu0007/pegasus_large_covid")

pegasus_large_covid_model = AutoModelForSeq2SeqLM.from_pretrained("mayu0007/pegasus_large_covid")

def SummarizeText(inp):  
   
    summary_generated = bert_model(inp)
#     print(summary_generated)
    
    inputs = tokenizer.encode("summarize: " + inp, return_tensors="pt", max_length=1024, truncation=True)
    outputs = model.generate(
        inputs, 
        max_length=128, 
        min_length=10, 
        length_penalty=2.0, 
        num_beams=4, 
        early_stopping=True)
    
    inputs_pegasus_large_covid = pegasus_large_covid_tokenizer.encode("summarize: " + inp, return_tensors="pt", max_length=1024, truncation=True)
    outputs_pegasus_large_covid = pegasus_large_covid_model.generate(
        inputs, 
        max_length=150, 
        min_length=50, 
        length_penalty=2.0, 
        num_beams=4, 
        early_stopping=True)
    
    summary_generated_pegasus_pubmed = tokenizer.decode(outputs[0])
    summary_pegasus_large_covid = pegasus_large_covid_tokenizer.decode(outputs_pegasus_large_covid[0])
    return summary_generated , summary_generated_pegasus_pubmed,summary_pegasus_large_covid

iface = gr.Interface(
  fn=SummarizeText, 
  inputs=[gr.inputs.Textbox(label="Abstract (*Enter paragraphs)",lines=10, placeholder="Enter abstract text here...") ],
    
  outputs=[
           gr.outputs.Textbox(label=" Summary-1  (Bert)") ,
           gr.outputs.Textbox(label=" Summary-2 (google/pegasus-pubmed) ") ,
           gr.outputs.Textbox(label=" Summary-2 (mayu0007/pegasus_large_covid) ")],title= "Auto summarization and Summary comparision(beta)"  )
iface.launch(debug=True)